In [1]:
import cv2
import numpy as np

## Load/Read image

In [2]:
# Load as image using 'imread' specifying the path to image
img=cv2.imread(r"C:\Users\DELL'\Desktop\img_1725-1.webp",1)

In [3]:
print(img)

[[[ 96 163 227]
  [ 96 163 227]
  [ 96 163 227]
  ...
  [120 228 251]
  [120 228 251]
  [120 228 251]]

 [[ 96 163 227]
  [ 96 163 227]
  [ 96 163 227]
  ...
  [120 228 251]
  [120 228 251]
  [120 228 251]]

 [[ 96 163 227]
  [ 96 163 227]
  [ 96 163 227]
  ...
  [120 228 251]
  [120 228 251]
  [120 228 251]]

 ...

 [[102 205 225]
  [102 205 225]
  [102 205 225]
  ...
  [ 96 171 246]
  [ 96 171 246]
  [ 96 171 246]]

 [[102 205 225]
  [102 205 225]
  [102 205 225]
  ...
  [ 96 171 246]
  [ 96 171 246]
  [ 96 171 246]]

 [[101 204 223]
  [101 204 223]
  [101 204 223]
  ...
  [ 93 170 246]
  [ 93 170 246]
  [ 93 170 246]]]


## Shape gives the dimensions of the image array

In [4]:
#the 3D dimentions are 954 pixel in height * 1290 pixels wide
#3 means that there are 3 components (RGB) that make up this image
img.shape

(945, 1290, 3)

## Display the image

In [5]:
# To display ur image variable, we use 'imshow'
# The first parameter will be title shown on image window
# The second parameter is the image variable
cv2.imshow('SRK',img)

# 'waitKey' allows us to input information when a image window is open  
# By leaving it blank it just waits for anykey to be pressed before continouing.
# By placing numbers (except 0), we can specify a delay for
# how long you keep the window open (time is in milliseconds here)

cv2.waitKey(2000)

#this closes all open windows 
# Failure to place this will cause your program to hand

cv2.destroyAllWindows()

In [6]:
img=cv2.imread("Desktop\img_1725-1.webp")
cv2.imshow('KINGKHAN',img)
cv2.waitKey()
cv2.destroyAllWindows()

## Save image

In [7]:
# Simple use 'imwrite' specificing the file name and the image to be saved
cv2.imwrite("WEBP_File(.webp)",img)

True

## Resize Image

In [8]:
img=cv2.imread("Desktop\img_1725-1.webp")
               
resized_image=cv2.resize(img,(300,200))

gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

cv2.imshow("Shahrukh Image", gray)

cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
img.shape[0]*0.5

472.5

In [10]:
img.shape[1]*0.5

645.0

## Face Detection using HAAR Cascade Classifiers

In [11]:
# We point openCV's CascadeClassifier function to where our classifier (XML file format) is stored
face_classifier=cv2.CascadeClassifier(r"C:\Users\DELL'\Downloads\Haarcascades/haarcascade_frontalface_default.xml")

# Loud our image then convert is to grayscale
image=cv2.imread("Desktop\img_1725-1.webp")
image=cv2.resize(img,(200,300))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# Tuning Cascade Classifiers - detectMultiScale(input image, **Scale Factor**, **MIN Neighbors**)
faces = face_classifier.detectMultiScale(gray, 1.05, 5)

In [12]:
print(faces)

[[60 52 95 95]]


In [13]:
face_classifier=cv2.CascadeClassifier(r"C:\Users\DELL'\Downloads\Haarcascades\haarcascade_frontalface_default.xml")

img=cv2.imread("Desktop\img_1725-1.webp")
resized_image=cv2.resize(img,(200,300))
gray=cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray, 1.05,5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No faces found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+y,y+h), (0,255,100),1)
    
cv2.imshow("Face Detection", image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\DELL'\AppData\Local\Temp\ipykernel_8896\3694044712.py:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


## Face & Eye detection using HAAR Cascade Classifiers in image

In [14]:
face_classifier=cv2.CascadeClassifier(r"C:\Users\DELL'\Downloads\Haarcascades\haarcascade_frontalface_default.xml")
eye_classifier=cv2.CascadeClassifier(r"C:\Users\DELL'\Downloads\Haarcascades\haarcascade_eye.xml")

img=cv2.imread("Desktop\img_1725-1.webp")
resized_image=cv2.resize(img,(200,300))
gray=cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray, 1.03,5)

if faces is ():
    print("No faces found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y), (x+w,y+h), (255,0,0), 2)
    roi_gray=gray[y:y+h, x:x+w]
    roi_color=resized_image[y:y+h, x:x+w]
    eyes=eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh), (0,255,0), 2)
        
cv2.imshow("img", resized_image)
cv2.waitKey(0)

cv2.destroyAllWindows()

<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\DELL'\AppData\Local\Temp\ipykernel_8896\4005412469.py:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


## Capture a video

In [15]:
# doing some Face Recognition with the webcam

import cv2
video = cv2.VideoCapture(0) #0--webcam

while True:
    check, frame=video.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow("VIdeo", gray)
    if cv2.waitKey(1) == ord("q"):
        break
        
video.release()
cv2.destroyAllWindows()

## Face & Eyes Detection using HAAR Cascade Classifiers

In [16]:
## Defining a function that will do the detections
face_cascade = cv2.CascadeClassifier(r"C:\Users\DELL'\Downloads\Haarcascades\haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(r"C:\Users\DELL'\Downloads\Haarcascades\haarcascade_eye.xml")

def detect(gray, frame):
    faces = face_classifier.detectMultiScale(gray, 1.03, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 2)
        roi_gray = gray[y:y + h, x:x + w]
        roi_color = frame[y:y + h, x:x + w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.1,3)  # Corrected here
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 2)
    return frame

# Doing some Face Recognition with the webcam
video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas=detect(gray, frame)
    cv2.imshow("Video", canvas)
    if cv2.waitKey(1)==ord("q"):
        break
    
video.release()
cv2.destroAllWindows()


AttributeError: module 'cv2' has no attribute 'destroAllWindows'

## Pedistrian Detection

In [ ]:
import cv2

#creat our body classifier
body_classifier=cv2.CascadeClassifier(r'D:\Haarcascades\haarcascade_fullbody.xml')

#Initiate video capture for video file
# cap=cv2.VideoCapture(r"‪D:\walking (1).avi")
cap=cv2.VideoCapture(r'D:\walking (1).avi')

#Loop once video is succesfully loaded
while cap.isOpened():
    
    #read first frame
    check, frame=cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # pass frame to our body classifier
    bodies=body_classifier.detectMultiScale(gray, 1.2, 3)
    
    #extract bounding boxes for any bodies identified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255), 2)
        cv2.imshow("Pedestrians", frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2

# cap=cv2.VideoCapture(r'D:\walking (1).avi')
cap=cv2.VideoCapture(r'D:\walking (1).avi')
check, frame=cap.read()


In [ ]:
import time

#Create our body classifier
car_classifier=cv2.CascadeClassifier(r'D:\Haarcascades\haarcascade_car.xml')

# Initiate video capture for video file
cap=cv2.VideoCapture(r"D:\\cars.avi")

# Loop once video is succesfully loaded
while cap.isOpened():
    
    time.sleep(.05)
    #read first frame
    check, frame=cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # pass frame to our car classifier
    cars=car_classifier.detectMultiScale(gray, 1.4,2)
    
    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255), 2)
        cv2.imshow('Cars', frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
cap=cv2.VideoCapture(r"D:\cars.avi")
while cap.isOpened():
    i, frame = cap.read()
    f1 = cv2.resize(frame, (700,500))
    cv2.imshow('frame',f1)
    
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()